### ISSUE TITLE
otf2fea emits empty lookups

### ISSUE THREAD

**Issue by bdenckla** [simoncozens/fontFeatures#44]
Probably this is some pathology in the font, i.e. otf2fea isn't really to blame, but it would be nice if ot2fea were smart enough to suppress empty lookups (perhaps just emitting a comment to that effect). They upset FontForge, for one.

**Comment by bdenckla** [comment]
Here is a zip file of a `.ttf` and a corresponding `.fea` produced by otf2fea, illustrating this issue, as well as 3 other minor issues I've reported today, #43, #42, & #41.
[TaameyFrankCLM-Medium-0d110-orig.zip](https://github.com/simoncozens/fontFeatures/files/6437753/TaameyFrankCLM-Medium-0d110-orig.zip)
Here is an example of this issue (also showing the empty statement (bare semicolon) issue) (including lots of vertical whitespace in case that is a helpful clue):
```
lookup MarkToMark55 {
    lookupflag RightToLeft;
    ;
    # Original source: 21 
            

            

            

} MarkToMark55;
```

**Comment by simoncozens** [comment]
This seems to have been fixed in 79b139f - please try using the latest version from git. (I'm hoping to cut a 2.0 release soon.)

**Comment by bdenckla** [comment]
Still happens with latest `fontfeatures` module.

My procedure was to do `pip install -e` on a clone of the latest `fontfeatures` repo, and then run `otf2fea` again.

I saw various small changes in the output, giving me some confidence that indeed I was using the latest `fontfeatures`, but I saw no change regarding the empty `mkmk` lookups.
